language: node_js
sudo: required
install: true
node_js:
  - "iojs"
  - "7"
before_script:
  - chmod +x ./.travis/upload-to-repo.sh
  - sed -i -e 's/\r$//' ./.travis/upload-to-repo.sh
script: 
  - mkdir -p /home/travis/repository
addons:
  sonarcloud:
    organization: "welle-github" # the key of the org you chose at step #3
cache:
  directories:
    - '$HOME/.sonar/cache'